// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/generate-blog-post.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var generate_blog_post_default = defineTool({
  name: "generate_blog_post",
  title: "Generate a home improvement blog post",
  description: "Generate a KLR Build blog article about an interior or exterior home improvement topic using Lovable AI. Returns a ~300-400 word article with practical tips, cost guidance, and actionable advice.",
  inputSchema: {
    topic: z.string().describe("The blog post topic, e.g. 'Modern Kitchen Renovation Ideas'."),
    type: z.enum(["interior", "exterior"]).describe("Whether the topic is interior or exterior home improvement.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ topic, type }) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      return { content: [{ type: "text", text: "LOVABLE_API_KEY is not configured on the server." }], isError: true };
    }
    const systemPrompt = "You are an expert home improvement writer for KLR Build, a family-owned general B construction company in Oceanside, CA. Write engaging, practical blog posts that provide real value to homeowners. Include specific tips, cost estimates, and actionable advice. Keep the tone professional yet conversational.";
    const userPrompt = type === "interior" ? `Write a comprehensive blog post about ${topic} for interior home improvement. Include practical tips, design ideas, and budget considerations. Make it around 300-400 words.` : `Write a comprehensive blog post about ${topic} for exterior home improvement. Include practical tips, materials recommendations, and maintenance advice. Make it around 300-400 words.`;
    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt }
        ]
      })
    });
    if (!response.ok) {
      const text = await response.text();
      return {
        content: [{ type: "text", text: `AI gateway error (${response.status}): ${text}` }],
        isError: true
      };
    }
    const data = await response.json();
    const content = data.choices?.[0]?.message?.content ?? "";
    return {
      content: [{ type: "text", text: `# ${topic}

${content}` }],
      structuredContent: { title: topic, type, article: content }
    };
  }
});

// src/lib/mcp/tools/company-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var INFO = {
  name: "KLR Build",
  description: "Family-owned general B construction company serving Southern California.",
  address: "697 Chimney Rock Drive, Oceanside, CA 92058",
  phone: "(619) 739-1135",
  website: "https://www.klrbuild.com",
  services: [
    "Interior remodels (kitchens, bathrooms, living spaces)",
    "Exterior improvements (decks, siding, curb appeal)",
    "Home additions",
    "New construction",
    "Custom carpentry & finishes"
  ]
};
var company_info_default = defineTool2({
  name: "get_company_info",
  title: "Get KLR Build company info",
  description: "Return contact information and a summary of services offered by KLR Build.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO, null, 2) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/index.ts
var projectRef = "tadbcnnfjigbagcmypvp";
var mcp_default = defineMcp({
  name: "klr-build-mcp",
  title: "KLR Build MCP",
  version: "0.1.0",
  instructions: "Tools for KLR Build, a family-owned general B construction company. Use `get_company_info` for contact details and services, and `generate_blog_post` to draft interior or exterior home-improvement articles.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [company_info_default, generate_blog_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
